version: '3'

networks:
  monitoring_network:
    external: true

volumes:
  prometheus_data:
  grafana_data:

services:
  node_exporter:
    image: edvaldoszy/prometheus-node-exporter:0.18.1-alpine
    hostname: '{{.Node.Hostname}}'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - monitoring_network
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.filesystem.ignored-fs-types=^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$'
    deploy:
      mode: global

  cadvisor:
    image: google/cadvisor:latest
    hostname: '{{.Node.Hostname}}'
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:rw
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring_network
    deploy:
      mode: global

  prometheus:
    image: edvaldoszy/prometheus:2.11.1-alpine
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/var/lib/prometheus
    ports:
      - 9090:9090
    networks:
      - monitoring_network
    deploy:
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - ./env/grafana.env
    ports:
      - 3000:3000
    networks:
      - monitoring_network
    deploy:
      placement:
        constraints:
          - node.role == manager
