version: '3'

networks:
  portainer_network:
    external:
      name: portainer_network

volumes:
  portainer_data:

services:
  agent:
    image: portainer/agent:1.4.0
    env_file:
      - portainer.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer:1.22.0
    env_file:
      - portainer.env
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - portainer_data:/data
    networks:
      - portainer_network
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
