global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node-exporter
    dns_sd_configs:
      - type: A
        port: 9100
        names: ['tasks.node_exporter']
  
  - job_name: api
    metrics_path: '/swagger-stats/metrics'
    dns_sd_configs:
      - type: A
        port: 3001
        names: ['tasks.api']
